/* pages/Vendors.jsx — FY 2026-27
   Vendor Master — central source of truth for Invoices & Payments.
   • Sequential IDs: VEN00001, VEN00002 … (generated by backend)
   • Fields: Vendor ID, Name, GST, Address, Contact, Email, Phone, Created
   • Add / Edit / Delete / Search
   • Duplicate prevention via backend (409 response)
*/
import { useEffect, useState } from "react";
import {
  T, Badge, TH, TD, IS, Field, Modal, Btn, SearchBar,
  PageHeader, PAGE_STYLE, Card,
} from "./shared";

const VCAT     = ["Software","Infrastructure","Hardware","Consulting","Maintenance","AMC","Other"];
const CONTRACT = ["AMC","Project","Retainer","One-time"];

const tkn  = () => localStorage.getItem("token") || "";
const hdr  = () => ({ Authorization: `Bearer ${tkn()}` });
const hdrJ = () => ({ ...hdr(), "Content-Type": "application/json" });

/* ── Delete Confirm ──────────────────────────────────────────── */
function DeleteConfirm({ vendor, onConfirm, onClose }) {
  return (
    <Modal title="Delete Vendor" onClose={onClose} width={420}>
      <p style={{ fontSize: 13, color: T.sub, fontFamily: "'DM Sans',sans-serif", marginBottom: 20 }}>
        Delete <b>"{vendor.name}"</b>? This cannot be undone. Vendors with linked invoices cannot be deleted.
      </p>
      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
        <Btn variant="secondary" onClick={onClose}>Cancel</Btn>
        <Btn variant="danger" onClick={onConfirm}>Delete Vendor</Btn>
      </div>
    </Modal>
  );
}

/* ── Add / Edit Modal ────────────────────────────────────────── */
function VendorModal({ vendor, onClose, onSaved }) {
  const isEdit = !!vendor;
  const BLANK  = { name:"", vendorCode:"", category:"", contractType:"", contactPerson:"", email:"", phone:"", gstNumber:"", address:"" };
  const [form,   setForm]   = useState(isEdit ? { ...vendor } : BLANK);
  const [saving, setSaving] = useState(false);
  const [error,  setError]  = useState("");
  const F = (k, v) => setForm(f => ({ ...f, [k]: v }));

  const save = async () => {
    if (!form.name.trim()) { setError("Vendor Name is required."); return; }
    setSaving(true); setError("");
    try {
      const method = isEdit ? "PATCH" : "POST";
      const url    = isEdit ? `/api/vendors/${vendor.id}` : "/api/vendors";
      const r      = await fetch(url, { method, headers: hdrJ(), body: JSON.stringify(form) });
      const json   = await r.json();
      if (!r.ok) { setError(json.error || "Failed to save."); return; }
      onSaved(); onClose();
    } catch (e) { setError(e.message); }
    finally { setSaving(false); }
  };

  return (
    <Modal title={isEdit ? `Edit — ${vendor.name}` : "Add New Vendor"} onClose={onClose} width={700}>
      {error && (
        <div style={{ background: "#FFF1F3", border: `1px solid #FCA5A5`, borderRadius: 8, padding: "8px 14px", marginBottom: 14, fontSize: 12, color: T.rose, fontFamily: "'DM Sans',sans-serif" }}>
          {error}
        </div>
      )}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 }}>
        <Field label="Vendor Name" required>
          <input value={form.name} onChange={e => F("name", e.target.value)} style={IS} placeholder="e.g. TechSolutions India Pvt. Ltd."/>
        </Field>
        <Field label="Vendor Code">
          <input value={form.vendorCode || ""} onChange={e => F("vendorCode", e.target.value)} style={{ ...IS, background: "#F8FAFF", color: T.muted }} placeholder="Auto-generated if blank (VEN00001)"/>
        </Field>
        <Field label="GST Number">
          <input value={form.gstNumber || ""} onChange={e => F("gstNumber", e.target.value)} style={IS} placeholder="e.g. 29AAGCM2146G1ZV"/>
        </Field>
        <Field label="Category">
          <select value={form.category || ""} onChange={e => F("category", e.target.value)} style={IS}>
            <option value="">— Select —</option>
            {VCAT.map(o => <option key={o}>{o}</option>)}
          </select>
        </Field>
        <Field label="Contact Person">
          <input value={form.contactPerson || ""} onChange={e => F("contactPerson", e.target.value)} style={IS} placeholder="e.g. Ramesh Iyer"/>
        </Field>
        <Field label="Email">
          <input type="email" value={form.email || ""} onChange={e => F("email", e.target.value)} style={IS} placeholder="contact@vendor.com"/>
        </Field>
        <Field label="Phone">
          <input value={form.phone || ""} onChange={e => F("phone", e.target.value)} style={IS} placeholder="+91 98765 43210"/>
        </Field>
        <Field label="Contract Type">
          <select value={form.contractType || ""} onChange={e => F("contractType", e.target.value)} style={IS}>
            <option value="">— Select —</option>
            {CONTRACT.map(o => <option key={o}>{o}</option>)}
          </select>
        </Field>
        <div style={{ gridColumn: "1/-1" }}>
          <Field label="Address">
            <input value={form.address || ""} onChange={e => F("address", e.target.value)} style={IS} placeholder="Full registered address"/>
          </Field>
        </div>
      </div>
      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 20 }}>
        <Btn variant="secondary" onClick={onClose}>Cancel</Btn>
        <Btn onClick={save} disabled={!form.name.trim() || saving}>
          {saving ? "Saving…" : isEdit ? "Save Changes" : "Add Vendor"}
        </Btn>
      </div>
    </Modal>
  );
}

/* ══════════════════════════════════════════════════════════════
   MAIN
══════════════════════════════════════════════════════════════ */
export default function Vendors() {
  const [vendors,   setVendors]   = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [search,    setSearch]    = useState("");
  const [fCat,      setFCat]      = useState("");
  const [showAdd,   setShowAdd]   = useState(false);
  const [editV,     setEditV]     = useState(null);
  const [delV,      setDelV]      = useState(null);
  const [delError,  setDelError]  = useState("");

  const load = async () => {
    try {
      const r = await fetch("/api/vendors", { headers: hdr() });
      if (r.ok) setVendors(await r.json());
    } catch {}
  };

  useEffect(() => { load().finally(() => setLoading(false)); }, []);

  const handleDelete = async () => {
    setDelError("");
    const r = await fetch(`/api/vendors/${delV.id}`, { method: "DELETE", headers: hdr() });
    const json = await r.json();
    if (!r.ok) { setDelError(json.error || "Delete failed"); return; }
    setDelV(null); load();
  };

  const filtered = vendors.filter(v => {
    const q = search.toLowerCase();
    return (
      (!q || [v.name, v.vendorCode, v.gstNumber, v.contactPerson, v.email]
        .some(f => (f || "").toLowerCase().includes(q))) &&
      (!fCat || v.category === fCat)
    );
  });

  const kpis = [
    { label: "Total Vendors",  value: vendors.length,                                         color: T.teal   },
    { label: "Software",       value: vendors.filter(v => v.category === "Software").length,   color: T.indigo },
    { label: "Infrastructure", value: vendors.filter(v => v.category === "Infrastructure").length, color: T.violet },
    { label: "AMC",            value: vendors.filter(v => v.contractType === "AMC").length,    color: T.amber  },
    { label: "Auto-created",   value: vendors.filter(v => v.source === "auto-invoice").length, color: T.emerald},
  ];

  if (loading) return (
    <div style={{ ...PAGE_STYLE, paddingTop: 80, textAlign: "center", color: T.muted, fontFamily: "'DM Sans',sans-serif" }}>
      Loading vendors…
    </div>
  );

  return (
    <div style={PAGE_STYLE}>
      <PageHeader
        title="Vendors"
        sub="Vendor Master — source of truth for Invoices & Payments"
        badge="FY 2026-27"
        actions={
          <>
            <SearchBar value={search} onChange={setSearch} placeholder="Search name, code, GST…"/>
            <select value={fCat} onChange={e => setFCat(e.target.value)} style={{ ...IS, width: 150 }}>
              <option value="">All Categories</option>
              {VCAT.map(o => <option key={o}>{o}</option>)}
            </select>
            <Btn onClick={() => setShowAdd(true)}>+ Add Vendor</Btn>
          </>
        }
      />

      {/* KPI strip */}
      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>
        {kpis.map((s, i) => (
          <div key={i} style={{ background: T.card, border: `1px solid ${T.border}`, borderRadius: 10, padding: "10px 18px", boxShadow: "0 1px 3px rgba(0,0,0,0.04)" }}>
            <div style={{ fontSize: 9, color: T.muted, fontWeight: 700, letterSpacing: "0.09em", textTransform: "uppercase", fontFamily: "'DM Sans',sans-serif", marginBottom: 4 }}>{s.label}</div>
            <div style={{ fontSize: 17, fontWeight: 800, color: s.color, fontFamily: "'Plus Jakarta Sans',sans-serif" }}>{s.value}</div>
          </div>
        ))}
      </div>

      <Card style={{ padding: 0, overflow: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <TH>Vendor ID</TH>
              <TH>Vendor Name</TH>
              <TH>GST Number</TH>
              <TH>Contact Person</TH>
              <TH>Email</TH>
              <TH>Phone</TH>
              <TH>Category</TH>
              <TH>Created</TH>
              <TH right>Actions</TH>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 && (
              <tr><td colSpan={9} style={{ padding: 32, textAlign: "center", color: T.muted, fontFamily: "'DM Sans',sans-serif", fontSize: 13 }}>
                No vendors found. Click '+ Add Vendor' to add one.
              </td></tr>
            )}
            {filtered.map((v, i) => (
              <tr key={v.id || i}
                onMouseEnter={e => e.currentTarget.style.background = "#F7F9FF"}
                onMouseLeave={e => e.currentTarget.style.background = "transparent"}
                style={{ transition: "background 0.12s" }}>

                <TD>
                  <span style={{ fontFamily: "monospace", fontSize: 11, background: "#F0FDFA", color: T.teal, padding: "2px 8px", borderRadius: 5, fontWeight: 700, whiteSpace: "nowrap" }}>
                    {v.vendorCode || "—"}
                  </span>
                  {v.source === "auto-invoice" && (
                    <span style={{ fontSize: 9, color: T.muted, fontFamily: "'DM Sans',sans-serif", marginLeft: 6 }}>auto</span>
                  )}
                </TD>

                <TD bold>
                  <div style={{ fontSize: 13, fontWeight: 700, color: T.text, fontFamily: "'Plus Jakarta Sans',sans-serif", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 180 }}>{v.name}</div>
                  {v.address && <div style={{ fontSize: 10, color: T.muted, fontFamily: "'DM Sans',sans-serif", marginTop: 1, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 180 }}>{v.address.slice(0, 50)}{v.address.length > 50 ? "…" : ""}</div>}
                </TD>

                <TD><span style={{ fontFamily: "monospace", fontSize: 11, color: T.sub }}>{v.gstNumber || "—"}</span></TD>

                <TD>{v.contactPerson || "—"}</TD>

                <TD>
                  {v.email
                    ? <a href={`mailto:${v.email}`} style={{ color: T.indigo, fontSize: 12, fontFamily: "'DM Sans',sans-serif", textDecoration: "none" }}>{v.email}</a>
                    : "—"}
                </TD>

                <TD>{v.phone || "—"}</TD>

                <TD>
                  {v.category ? <Badge label={v.category} color={T.teal} bg="#F0FDFA"/> : "—"}
                </TD>

                <TD>
                  {v.createdAt
                    ? new Date(v.createdAt._seconds ? v.createdAt._seconds * 1000 : v.createdAt)
                        .toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "2-digit" })
                    : "—"}
                </TD>

                <TD right>
                  <div style={{ display: "flex", gap: 5, justifyContent: "flex-end" }}>
                    <Btn small variant="secondary" onClick={() => setEditV(v)}>Edit</Btn>
                    <Btn small variant="danger"    onClick={() => { setDelV(v); setDelError(""); }}>Delete</Btn>
                  </div>
                </TD>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>

      {/* Modals */}
      {showAdd && <VendorModal onClose={() => setShowAdd(false)} onSaved={() => { setShowAdd(false); load(); }}/>}
      {editV   && <VendorModal vendor={editV} onClose={() => setEditV(null)} onSaved={() => { setEditV(null); load(); }}/>}
      {delV    && (
        <DeleteConfirm
          vendor={delV}
          onConfirm={handleDelete}
          onClose={() => { setDelV(null); setDelError(""); }}
        />
      )}
      {/* Delete error (if vendor has linked invoices) */}
      {delError && (
        <div style={{ position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", background: "#FFF1F3", border: `1px solid #FCA5A5`, borderRadius: 10, padding: "12px 20px", fontSize: 13, color: T.rose, fontFamily: "'DM Sans',sans-serif", zIndex: 2000, boxShadow: "0 4px 20px rgba(0,0,0,0.15)" }}>
          {delError}
          <button onClick={() => setDelError("")} style={{ marginLeft: 12, background: "none", border: "none", cursor: "pointer", color: T.rose, fontWeight: 700 }}>×</button>
        </div>
      )}
    </div>
  );
}